services:
  mysql:
    image: "mysql"
    container_name: db_srv
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "logindb"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - /mysql-data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"


  